### ISSUE TITLE
Can you support using in Docker-Kong?

### ISSUE THREAD

**Issue by TDFS-Dom** [Optum/kong-upstream-jwt#1]
Can you support my run in Docker with a plugin?
<img width="1209" alt="screen shot 2018-03-27 at 12 58 12" src="https://user-images.githubusercontent.com/12974761/37949379-9715b51e-31be-11e8-8c7e-ebe4a066657b.png">

**Comment by rsbrisci** [comment]
Hi DevToanNH,

We use this plugin in our own dockerized deployment; it should be fully compatible. However, it looks like you might be having issues with luarocks itself.

Wondering if you can't install any other packages with it. 
`luarocks install inspect`

Does that error out as well?

**Comment by jeremyjpj0916** [comment]
Closing this as seems no further issues/response.
