### ISSUE TITLE
installation Instructions

### ISSUE THREAD

**Issue by eramirez-sv** [Optum/kong-upstream-jwt#2]
Hi,
I have followed the installation instruction and set up the environment variables. I am not seeing any JWT headers added to my requests. I then registered it as a custom_plugin on kong.conf and added to the service I am testing, still nothing shows up.  What am I missing, how can check whether the JWT header is being added?
Thanks,

**Comment by egobsv** [comment]
I see the JWT now after debugging, I kept getting a message saying that 'conf.ssl_cert' was missing. 
After adding the ssl_cert and ssl_cert_key inside kong.conf, it works now.

**Comment by eramirez-sv** [comment]
I see the JWT now after debugging, I kept getting a message saying that 'conf.ssl_cert' was missing. After adding the ssl_cert and ssl_cert_key inside kong.conf, it works now.

**Comment by jeremyjpj0916** [comment]
Yep just need the 

```
$ export KONG_SSL_CERT_KEY="/path/to/kong/ssl/privatekey.key"
$ export KONG_SSL_CERT_DER="/path/to/kong/ssl/kongpublickey.cer"
```
Environment variables as well with proper cert paths. These environment variables correspond to what is in the kong.conf as well. Glad you resolved it!
