### ISSUE TITLE
Incompatible with kong 3.x

### ISSUE THREAD

**Issue by skyreginag** [Optum/kong-upstream-jwt#29]
Hello, first thing first, thanks for your work!
I'd like to report that the plugin does not work on kong 3.x + due to this: https://github.com/Kong/kong/pull/8874 

(Partial) Stack trace:
Jul 07 12:19:56 ip-10-0-0-142 kong[25264]: Error: /usr/local/share/lua/5.1/kong/tools/utils.lua:710: error loading module 'kong.plugins.kong-upstream-jwt.handler':
Jul 07 12:19:56 ip-10-0-0-142 kong[25264]: .../share/lua/5.1/kong/plugins/kong-upstream-jwt/access.lua:4: module 'kong.singletons' not found:No LuaRocks module found for kong.singletons

**Comment by jeremyjpj0916** [comment]
@skyreginag Thanks for the feedback, if you have a chance to hack in the raw source code changes with your deployment feel free to try this: https://github.com/Optum/kong-upstream-jwt/pull/30 and see if that fixes all the errors you see and plugin is working for your use case once more!

**Comment by jeremyjpj0916** [comment]
Should be fixed w latest release so closing this.
