### ISSUE TITLE
JWT Token Should Contain More Information from Client

### ISSUE THREAD

**Issue by brianwyka** [Optum/kong-upstream-jwt#3]
JWT token should contain more information from client:

## Fields to include
* `aud` - Audience (https://tools.ietf.org/html/rfc7519#section-4.1.3)
* `jti` - JWT ID (https://tools.ietf.org/html/rfc7519#section-4.1.7)
* `consumerid` - Consumer ID (Custom)
* `consumername` - Consumer Username(Custom)

### Other fields to also consider
* `iss` - Issuer (https://tools.ietf.org/html/rfc7519#section-4.1.1)
* `iat` - Issued at (https://tools.ietf.org/html/rfc7519#section-4.1.6)

**Comment by jeremyjpj0916** [comment]
Codebase merged, addresses the issue here.
