### ISSUE TITLE
Add http authorization header as option for setting JWT token

### ISSUE THREAD

**Issue by fvnkerk** [Optum/kong-upstream-jwt#5]
Currently the generated token can be set in http header named 'jwt' or url param named 'jwt'. 

Ideally the http authorisation should be an option as well

**Comment by rsbrisci** [comment]
Hi @fvnkerk!
That should be pretty easy to code into the https://github.com/Optum/kong-upstream-jwt/blob/master/src/schema.lua and https://github.com/Optum/kong-upstream-jwt/blob/master/src/access.lua#L76

Maybe 2 fields in the schema, something like `header` & `credential type`, which would make it configurable.

I'd welcome a PR with those changes!

**Comment by row1govender** [comment]
Hi @rsbrisci ,

Been looking into a possible implementation for this issue.

Is it completely necessary to make `credential type` configurable?
The thinking is that we are only working with JWT tokens in this case, and by default the value for `credential type` will always be `Bearer`.

Looking into adding a `header` field, and defaulting the type to `Bearer` if header value is specified as `Authorization`

**Comment by jeremyjpj0916** [comment]
Closing this as work was done here for configurable header: 
https://github.com/Optum/kong-upstream-jwt/pull/9
